### ISSUE TITLE
ANY CHANCE THERE'S A SMALLER SIZE OF THE MODEL

### ISSUE THREAD

**Issue by sfxeazilove** [pterhoer/QMagFace#10]
Hi, i would love to know if there's a smaller size of the model, i understand the magface_epoch_00025.pth model file is around 207MB, is there a relatively lightweight Qmagface model

**Comment by mihlefeld** [comment]
QMagFace is merely a post-processing step on the scoring function of magface embeddings. You'll have to see if there is a smaller MagFace model and try QMagFace on that model
