### ISSUE TITLE
onnx model

### ISSUE THREAD

**Issue by MyraBaba** [pterhoer/QMagFace#12]
is there onnx exported model / example?

**Comment by mihlefeld** [comment]
No, we do not have an exported ONNX model of MagFace, and you should rather ask [here](https://github.com/IrvingMeng/MagFace).

**Comment by PonderForge** [comment]
@MyraBaba 
Happy Saint Patrick's Day! 
Here's an ONNX model of QMagFace:
https://drive.google.com/file/d/1wnB0_WtKgLc2sz6D2vdILDPnlXLcUZi4/view?usp=sharing
It looks like embed_images.py does not apply any mean or std, so you only need to divide images by 255, and swap GBR to RGB if you use OpenCV. 
(Although the ONNX model is not creating exactly the same output, it's roughly the same)

**Comment by MyraBaba** [comment]
@PonderForge 
Thanks. .. Best
