### ISSUE TITLE
training-related questions

### ISSUE THREAD

**Issue by onlyadragon** [pterhoer/QMagFace#13]
If I want to retrain on the CASIA-WebFace dataset now, but I didn't find any training code provided in the paper, only a pre-trained model was given. Should I retrain on the pre-trained model of MagFace and then incorporate the QMagFace method?

**Comment by mihlefeld** [comment]
QMagFace works on top of a fully trained MagFace model. If you want to use QMagFace with a MagFace model trained on CASIA-WebFace, then you first need to train MagFace using the [code ](https://github.com/IrvingMeng/MagFace) they published for that. Then you can incorporate QMagFace by using the provided [train function](https://github.com/pterhoer/QMagFace/blob/395797145da1b1b263cbe7fb1564c6ea91f55b23/similarity/qmagface.py#L21). For an example how to use the function you can look at one of the [experiments](https://github.com/pterhoer/QMagFace/blob/395797145da1b1b263cbe7fb1564c6ea91f55b23/experiments/single_image_benchmarks.py#L10).
