### ISSUE TITLE
problems about train

### ISSUE THREAD

**Issue by YjDai** [pterhoer/QMagFace#2]
when I use the function QMagFace.train,  the result beta always equals to 0, alpha equals to  0.5?
can you show more codes about training?

**Comment by pterhoer** [comment]
Code was updated and experiments were added.

**Comment by onlyadragon** [comment]
Hi there! I need to train QMagFace with a different dataset, but I couldn't find any training code in QMagFace. I only saw that a pre-trained model was used. So, if I want to train it now, what should I do?
