### ISSUE TITLE
Where is FNMR metric?

### ISSUE THREAD

**Issue by HOMGH** [pterhoer/QMagFace#3]
Hi, thanks for sharing the source code.
I noticed you have reported EER and FNMR at different FMR values. Just wondering where I can find the evaluation metric of FNMR at a specific FMR? In the following function: https://github.com/pterhoer/QMagFace/blob/395797145da1b1b263cbe7fb1564c6ea91f55b23/evaluation/metrics.py#L49, I can see only the accuracy and EER metrics.
Also in this function, what are threer and  thr, metrics?
Thank you in advance.

**Comment by mihlefeld** [comment]
Hello @HOMGH in https://github.com/pterhoer/QMagFace/blob/395797145da1b1b263cbe7fb1564c6ea91f55b23/evaluation/metrics.py#L64-L67 of metrics.py we compute the FNMR at the given fmr value, the fmr value is expected to be a string like "fmr1e-5" or "fmr0.001".

**Comment by HOMGH** [comment]
Got it. Thank you so much.
