### ISSUE TITLE
How to get QMagFace embeddings for evaluation?

### ISSUE THREAD

**Issue by HOMGH** [pterhoer/QMagFace#4]
Hi,
I download the precomputed MagFace embeddings and pairs files based on what you suggested in Readme file, and extracted them in the QMagFace root directory. So, by evaluating on such embeddings, I'm actually evaluating MagFace method (**MagFace: A Universal Representation for Face Recognition and Quality Assessment**), right?
So if I want to evaluate QMagFace (your own method), can I get the embeddings on different datasets (Like what we have for MagFace) without training your model?
Thanks.

**Comment by pterhoer** [comment]
Hi MOMGH,

For using QMagFace on a different database, you extract MagFace embeddings of this database and use the quality-aware comparison function Eq. 3 to compute the comparison scores.
For Eq. 3, you need the two trainable parameters alpha and beta. If you use the same pretrained-models as we did, you can simply use the parameters stated in Table I.
If you do any changes (in preprocessing or another model), you should retrain these parameters.
(It should only take seconds)

Best
Philipp
