### ISSUE TITLE
A quastion about evaluation on cplfw, cpf,...

### ISSUE THREAD

**Issue by HOMGH** [pterhoer/QMagFace#6]
Hi,
I could successfully evaluate on LFW dataset using the embeddings and filenames files you published in your document (under _data folder).
I have a question about the evaluation on other datasets like cplfw, morph, cfp, agedb,... that the pairs files are available in your documents as well. The problem is that the pairs.text files (under pairs folder) for such datasets are not compatible with the names of images in those datasets. For example the names of the images in cplfw dataset are "Aaron_Eckhart_1.jpg" ,.... but the names in pairs.txt file are 0.jpg, 1.jpg, 2.jpg,....
How can I relate these two?
Thanks for your help.

**Comment by mihlefeld** [comment]
Ok, so, i'm not sure why the pairs.txt has this format, but you can check out tha PairsDataset Class where we read the pairs.txt files and convert them to the corresponding filename in our precomputed embeddings https://github.com/pterhoer/QMagFace/blob/395797145da1b1b263cbe7fb1564c6ea91f55b23/datasets/paired.py#L112-L120

For some reason, the person who computed the cplfw embeddings, as well as a few of the other ones changed the file names of the images. If you want to compute your own embeddings on cplfw, you can use the pairs_CPLFW.txt from the official [CPLFW dataset](http://www.whdeng.cn/CPLFW/index.html?reload=true) by changing the pairs function:
https://github.com/pterhoer/QMagFace/blob/395797145da1b1b263cbe7fb1564c6ea91f55b23/datasets/paired.py#L98-L110
For example, you can split up the calfw and cplfw cases and add new functions for handling the different filenames from your embeddings and pairs txt file. Within these cases you should likely call a function somewhat similar to https://github.com/pterhoer/QMagFace/blob/395797145da1b1b263cbe7fb1564c6ea91f55b23/datasets/paired.py#L40-L66
(note, in pairs_CPLFW.txt, all pairs span 2 lines, this is different to the lfw pairs.txt)

I hope this will help you!
