### ISSUE TITLE
CANNOT FIND PRETRAINED MODEL

### ISSUE THREAD

**Issue by sfxeazilove** [pterhoer/QMagFace#9]
Hi, i cannot seem to find the pretrained model: `magface_epoch_00025.pth`

**Comment by mihlefeld** [comment]
There's a link in the ReadMe.md under "Installation"

**Comment by sfxeazilove** [comment]
@mihlefeld Thank you for showimg that, I have a question; i would like to know if there is another version of the model with a relatively smaller size and if not how can i achieve that?

Thank you
